# MIT License
#
# SPDX-FileCopyrightText: Copyright (c) 2024-2025 Zerocracy
# SPDX-License-Identifier: MIT
---
AllCops:
  Exclude:
    - 'vendor/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  NewCops: enable
Naming/FileName:
  Regex: '^[a-z0-9\-._]*$'
Style/GlobalVars:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
require:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance
