# SPDX-FileCopyrightText: Copyright (c) 2024-2026 Zerocracy
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/rultor-image:1.24.0
install: |-
  pdd -f /dev/null
  bundle install --no-color
merge:
  script: |-
    bundle exec rake
