# MIT License
#
# SPDX-FileCopyrightText: Copyright (c) 2024-2025 Zerocracy
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/rultor-image:1.23.1
install: |-
  pdd -f /dev/null
  bundle install --no-color
merge:
  script: |-
    bundle exec rake
